services:

  maharasa-apisales:
    build: .
    container_name: maharasa-apisales
    restart: unless-stopped 
    ports:
      - "8001:8000"   

    env_file:
      - .env
    networks:
      - rabbitmq_net

    volumes:
      - ./logs:/app/logs
networks:
  rabbitmq_net:
    external: true
    name: rabbitmq_default