services:

  maharasa-apisales:
    build: .
    container_name: maharasa-apisales
    restart: unless-stopped 
    ports:
      - "8001:8000"  # beda port dari backend lama

    env_file:
      - .env

    volumes:
      - ./logs:/app/logs